### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by madelynnblue** [runningwild/gorbis#1]
Could you please add a license so this is usable?

**Comment by runningwild** [comment]
Done.  Although if you haven't noticed I haven't touched this code in 2 years.  This was entirely for fun and I ended up just using fmod instead.  I also have some minimal bindings for fmod if you're interested in using those.

**Comment by madelynnblue** [comment]
Thanks. I did notice, and have been making updates to bring it up to go 1.2. I'm not sure if I'm going to use it for my project or not, yet. I'm looking for a 100% go-based solution, so it's either make my own, or update yours and remove the fftw dependency.
